# Copyright (c) 2023-2025 Christian Hinkle, Brian Hinkle.

# Set this variable for the person including us to use.
set(FILES_CMAKE_RESULT
  # List out all our include files.
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_FULL}_Export.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_FULL}_include_export.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/Lifetime.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/Lifetime.inl"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/Concepts.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/Math.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/Math.inl"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/Raii.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/StringSpan.h"
  "${CMAKE_CURRENT_SOURCE_DIR}/Files/${MY_BASE_PROJECT_NAME_NAMESPACE}/${MY_BASE_PROJECT_NAME_LEAFNAME}/StringSpan.inl"
  )
